// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:scraper/src/scraper_bindings_generated.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void scraper_free_string(
  ffi.Pointer<ffi.Char> s,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Int64>, ffi.Int)>()
external void scraper_free_handle_array(
  ffi.Pointer<ffi.Int64> arr,
  int _len,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int scraper_parse(
  ffi.Pointer<ffi.Char> html,
  ffi.Pointer<ffi.Char> base_uri,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int scraper_parse_fragment(
  ffi.Pointer<ffi.Char> html,
  ffi.Pointer<ffi.Char> base_uri,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external int scraper_select(
  int handle,
  ffi.Pointer<ffi.Char> selector,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external int scraper_select_first(
  int handle,
  ffi.Pointer<ffi.Char> selector,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> scraper_attr(
  int handle,
  ffi.Pointer<ffi.Char> key,
);

@ffi.Native<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external int scraper_has_attr(
  int handle,
  ffi.Pointer<ffi.Char> key,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_text(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_own_text(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_inner_html(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_outer_html(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_tag_name(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_id(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_class_name(
  int handle,
);

@ffi.Native<ffi.Int Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external int scraper_has_class(
  int handle,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_data(
  int handle,
);

@ffi.Native<ffi.Int Function(ffi.Int64)>()
external int scraper_list_size(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int)>()
external int scraper_list_get(
  int handle,
  int index,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int scraper_list_first(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int scraper_list_last(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int scraper_parent(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int scraper_children(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int scraper_next_sibling(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int scraper_prev_sibling(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int scraper_siblings(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_node_name(
  int handle,
);

@ffi.Native<ffi.Int Function(ffi.Int64)>()
external int scraper_child_node_size(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Int)>()
external int scraper_child_node(
  int handle,
  int index,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Int>)>()
external void scraper_child_node_handles(
  int handle,
  ffi.Pointer<ffi.Pointer<ffi.Int64>> out_handles,
  ffi.Pointer<ffi.Int> out_len,
);

@ffi.Native<ffi.Int Function(ffi.Int64)>()
external int scraper_is_text_node(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int scraper_parent_node(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_node_outer_html(
  int handle,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Pointer<ffi.Int64>>, ffi.Pointer<ffi.Int>)>()
external void scraper_text_node_handles(
  int handle,
  ffi.Pointer<ffi.Pointer<ffi.Int64>> out_handles,
  ffi.Pointer<ffi.Int> out_len,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_text_node_text(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_text_node_whole_text(
  int handle,
);

@ffi.Native<ffi.Int Function(ffi.Int64)>()
external int scraper_text_node_is_blank(
  int handle,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<ffi.Char>)>()
external int scraper_create_element(
  ffi.Pointer<ffi.Char> tag,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<ffi.Char>)>()
external int scraper_create_text_node(
  ffi.Pointer<ffi.Char> text,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<ffi.Int64>, ffi.Int)>()
external int scraper_create_elements(
  ffi.Pointer<ffi.Int64> element_handles,
  int count,
);

@ffi.Native<ffi.Void Function(ffi.Int64)>()
external void scraper_free(
  int handle,
);

@ffi.Native<ffi.Void Function()>()
external void scraper_release_all();

@ffi.Native<ffi.Void Function()>()
external void scraper_dispose();

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external void scraper_set_attr(
  int handle,
  ffi.Pointer<ffi.Char> key,
  ffi.Pointer<ffi.Char> value,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external void scraper_remove_attr(
  int handle,
  ffi.Pointer<ffi.Char> key,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external void scraper_add_class(
  int handle,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external void scraper_remove_class(
  int handle,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external void scraper_set_text(
  int handle,
  ffi.Pointer<ffi.Char> text,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external void scraper_set_html(
  int handle,
  ffi.Pointer<ffi.Char> html,
);

@ffi.Native<ffi.Void Function(ffi.Int64)>()
external void scraper_remove_element(
  int handle,
);

@ffi.Native<ffi.Void Function(ffi.Int64)>()
external void scraper_remove_node(
  int handle,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external void scraper_prepend(
  int handle,
  ffi.Pointer<ffi.Char> html,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external void scraper_append(
  int handle,
  ffi.Pointer<ffi.Char> html,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external void scraper_set_text_node_text(
  int handle,
  ffi.Pointer<ffi.Char> text,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> scraper_node_base_uri(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> scraper_node_abs_url(
  int handle,
  ffi.Pointer<ffi.Char> key,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external void scraper_set_node_base_uri(
  int handle,
  ffi.Pointer<ffi.Char> value,
);
