// ignore_for_file: camel_case_types, non_constant_identifier_names
// ignore_for_file: always_specify_types, lines_longer_than_80_chars
// ignore_for_file: unreachable_from_main, unused_element, type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:wasm3/src/wasm3_bindings_generated.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.UintPtr>()
external int __security_cookie;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_none;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_mallocFailed;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_incompatibleWasmVersion;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_wasmMalformed;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_misorderedWasmSection;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_wasmUnderrun;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_wasmOverrun;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_wasmMissingInitExpr;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_lebOverflow;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_missingUTF8;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_wasmSectionUnderrun;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_wasmSectionOverrun;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_invalidTypeId;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_tooManyMemorySections;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_tooManyArgsRets;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_moduleNotLinked;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_moduleAlreadyLinked;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_functionLookupFailed;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_functionImportMissing;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_malformedFunctionSignature;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_noCompiler;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_unknownOpcode;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_restrictedOpcode;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_functionStackOverflow;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_functionStackUnderrun;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_mallocFailedCodePage;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_settingImmutableGlobal;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_typeMismatch;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_typeCountMismatch;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_missingCompiledCode;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_wasmMemoryOverflow;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_globalMemoryNotAllocated;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_globaIndexOutOfBounds;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_argumentCountMismatch;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_argumentTypeMismatch;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_globalLookupFailed;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_globalTypeMismatch;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_globalNotMutable;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapOutOfBoundsMemoryAccess;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapDivisionByZero;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapIntegerOverflow;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapIntegerConversion;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapIndirectCallTypeMismatch;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapTableIndexOutOfRange;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapTableElementIsNull;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapExit;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapAbort;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapUnreachable;

@ffi.Native<ffi.Pointer<ffi.Char>>()
external final ffi.Pointer<ffi.Char> m3Err_trapStackOverflow;

@ffi.Native<ffi.Pointer<M3Environment> Function()>()
external ffi.Pointer<M3Environment> m3_NewEnvironment();

@ffi.Native<ffi.Void Function(ffi.Pointer<M3Environment>)>()
external void m3_FreeEnvironment(
  ffi.Pointer<M3Environment> i_environment,
);

@ffi.Native<
  ffi.Pointer<M3Runtime> Function(
    ffi.Pointer<M3Environment>,
    ffi.Uint32,
    ffi.Pointer<ffi.Void>,
  )
>()
external ffi.Pointer<M3Runtime> m3_NewRuntime(
  ffi.Pointer<M3Environment> io_environment,
  int i_stackSizeInBytes,
  ffi.Pointer<ffi.Void> i_userdata,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<M3Runtime>)>()
external void m3_FreeRuntime(
  ffi.Pointer<M3Runtime> i_runtime,
);

@ffi.Native<
  ffi.Pointer<ffi.Uint8> Function(
    ffi.Pointer<M3Runtime>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Uint8> m3_GetMemory(
  ffi.Pointer<M3Runtime> i_runtime,
  ffi.Pointer<ffi.Uint32> o_memorySizeInBytes,
  int i_memoryIndex,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<M3Runtime>)>()
external int m3_GetMemorySize(
  ffi.Pointer<M3Runtime> i_runtime,
);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<M3Runtime>)>()
external ffi.Pointer<ffi.Void> m3_GetUserData(
  ffi.Pointer<M3Runtime> i_runtime,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<M3Environment>,
    ffi.Pointer<ffi.Pointer<M3Module>>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
  )
>()
external ffi.Pointer<ffi.Char> m3_ParseModule(
  ffi.Pointer<M3Environment> i_environment,
  ffi.Pointer<ffi.Pointer<M3Module>> o_module,
  ffi.Pointer<ffi.Uint8> i_wasmBytes,
  int i_numWasmBytes,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<M3Module>)>()
external void m3_FreeModule(
  ffi.Pointer<M3Module> i_module,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<M3Runtime>, ffi.Pointer<M3Module>)
>()
external ffi.Pointer<ffi.Char> m3_LoadModule(
  ffi.Pointer<M3Runtime> io_runtime,
  ffi.Pointer<M3Module> io_module,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<M3Module>)>()
external ffi.Pointer<ffi.Char> m3_RunStart(
  ffi.Pointer<M3Module> i_module,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<M3Module>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    M3RawCall,
    ffi.Pointer<ffi.Void>,
  )
>()
external ffi.Pointer<ffi.Char> m3_LinkRawFunctionEx(
  ffi.Pointer<M3Module> io_module,
  ffi.Pointer<ffi.Char> i_moduleName,
  ffi.Pointer<ffi.Char> i_functionName,
  ffi.Pointer<ffi.Char> i_signature,
  M3RawCall i_function,
  ffi.Pointer<ffi.Void> i_userdata,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Pointer<M3Function>>,
    ffi.Pointer<M3Runtime>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Char> m3_FindFunction(
  ffi.Pointer<ffi.Pointer<M3Function>> o_function,
  ffi.Pointer<M3Runtime> i_runtime,
  ffi.Pointer<ffi.Char> i_functionName,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<M3Function>)>()
external int m3_GetArgCount(
  ffi.Pointer<M3Function> i_function,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<M3Function>)>()
external int m3_GetRetCount(
  ffi.Pointer<M3Function> i_function,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<M3Function>, ffi.Uint32)>(
  symbol: 'm3_GetArgType',
)
external int _m3_GetArgType(
  ffi.Pointer<M3Function> i_function,
  int i_index,
);

M3ValueType m3_GetArgType(
  ffi.Pointer<M3Function> i_function,
  int i_index,
) => M3ValueType.fromValue(
  _m3_GetArgType(
    i_function,
    i_index,
  ),
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<M3Function>, ffi.Uint32)>(
  symbol: 'm3_GetRetType',
)
external int _m3_GetRetType(
  ffi.Pointer<M3Function> i_function,
  int i_index,
);

M3ValueType m3_GetRetType(
  ffi.Pointer<M3Function> i_function,
  int i_index,
) => M3ValueType.fromValue(
  _m3_GetRetType(
    i_function,
    i_index,
  ),
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<M3Function>,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
  )
>()
external ffi.Pointer<ffi.Char> m3_Call(
  ffi.Pointer<M3Function> i_function,
  int i_argc,
  ffi.Pointer<ffi.Pointer<ffi.Void>> i_argptrs,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<M3Function>,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
  )
>()
external ffi.Pointer<ffi.Char> m3_GetResults(
  ffi.Pointer<M3Function> i_function,
  int i_retc,
  ffi.Pointer<ffi.Pointer<ffi.Void>> o_retptrs,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<M3Runtime>, ffi.Pointer<M3ErrorInfo>)
>()
external void m3_GetErrorInfo(
  ffi.Pointer<M3Runtime> i_runtime,
  ffi.Pointer<M3ErrorInfo> o_info,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<M3Runtime>)>()
external void m3_ResetErrorInfo(
  ffi.Pointer<M3Runtime> i_runtime,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<M3Function>)>()
external ffi.Pointer<ffi.Char> m3_GetFunctionName(
  ffi.Pointer<M3Function> i_function,
);

final class M3Environment extends ffi.Opaque {}

final class M3Runtime extends ffi.Opaque {}

final class M3Module extends ffi.Opaque {}

final class M3Function extends ffi.Opaque {}

final class M3ErrorInfo extends ffi.Struct {
  external ffi.Pointer<ffi.Char> result;

  external ffi.Pointer<M3Runtime> runtime;

  external ffi.Pointer<M3Module> module;

  external ffi.Pointer<M3Function> function;

  external ffi.Pointer<ffi.Char> file;

  @ffi.Uint32()
  external int line;

  external ffi.Pointer<ffi.Char> message;
}

enum M3ValueType {
  c_m3Type_none(0),
  c_m3Type_i32(1),
  c_m3Type_i64(2),
  c_m3Type_f32(3),
  c_m3Type_f64(4),
  c_m3Type_unknown(5)
  ;

  final int value;
  const M3ValueType(this.value);

  static M3ValueType fromValue(int value) => switch (value) {
    0 => c_m3Type_none,
    1 => c_m3Type_i32,
    2 => c_m3Type_i64,
    3 => c_m3Type_f32,
    4 => c_m3Type_f64,
    5 => c_m3Type_unknown,
    _ => throw ArgumentError('Unknown value for M3ValueType: $value'),
  };
}

final class M3ImportContext extends ffi.Struct {
  external ffi.Pointer<ffi.Void> userdata;

  external ffi.Pointer<M3Function> function;
}

typedef M3RawCall =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<M3Runtime> runtime,
          ffi.Pointer<M3ImportContext> _ctx,
          ffi.Pointer<ffi.Uint64> _sp,
          ffi.Pointer<ffi.Void> _mem,
        )
      >
    >;

const int M3_VERSION_MAJOR = 0;

const int M3_VERSION_MINOR = 5;

const int M3_VERSION_REV = 1;

const String M3_VERSION = '0.5.1';

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int _WCHAR_T_DEFINED = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_CXX23 = 0;

const int _HAS_CXX26 = 0;

const int _HAS_NODISCARD = 1;

const int _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE = 1;

const int _CRT_BUILD_DESKTOP_APP = 1;

const int _UCRT_DISABLED_WARNINGS = 4324;

const int _ARGMAX = 100;

const int _TRUNCATE = -1;

const int _CRT_INT_MAX = 2147483647;

const int _CRT_SIZE_MAX = -1;

const String __FILEW__ = 'C';

const int _CRT_FUNCTIONS_REQUIRED = 1;

const int _CRT_HAS_CXX17 = 0;

const int _CRT_HAS_C11 = 0;

const int _CRT_INTERNAL_NONSTDC_NAMES = 1;

const int __STDC_SECURE_LIB__ = 200411;

const int __GOT_SECURE_LIB__ = 200411;

const int __STDC_WANT_SECURE_LIB__ = 1;

const int _SECURECRT_FILL_BUFFER_PATTERN = 254;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = 0;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES = 1;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY = 0;

const int _STATIC_INLINE_UCRT_FUNCTIONS = 1;

const int _MAX_ITOSTR_BASE16_COUNT = 9;

const int _MAX_ITOSTR_BASE10_COUNT = 12;

const int _MAX_ITOSTR_BASE8_COUNT = 12;

const int _MAX_ITOSTR_BASE2_COUNT = 33;

const int _MAX_LTOSTR_BASE16_COUNT = 9;

const int _MAX_LTOSTR_BASE10_COUNT = 12;

const int _MAX_LTOSTR_BASE8_COUNT = 12;

const int _MAX_LTOSTR_BASE2_COUNT = 33;

const int _MAX_ULTOSTR_BASE16_COUNT = 9;

const int _MAX_ULTOSTR_BASE10_COUNT = 11;

const int _MAX_ULTOSTR_BASE8_COUNT = 12;

const int _MAX_ULTOSTR_BASE2_COUNT = 33;

const int _MAX_I64TOSTR_BASE16_COUNT = 17;

const int _MAX_I64TOSTR_BASE10_COUNT = 21;

const int _MAX_I64TOSTR_BASE8_COUNT = 23;

const int _MAX_I64TOSTR_BASE2_COUNT = 65;

const int _MAX_U64TOSTR_BASE16_COUNT = 17;

const int _MAX_U64TOSTR_BASE10_COUNT = 21;

const int _MAX_U64TOSTR_BASE8_COUNT = 23;

const int _MAX_U64TOSTR_BASE2_COUNT = 65;

const int CHAR_BIT = 8;

const int SCHAR_MIN = -128;

const int SCHAR_MAX = 127;

const int UCHAR_MAX = 255;

const int CHAR_MIN = -128;

const int CHAR_MAX = 127;

const int MB_LEN_MAX = 5;

const int SHRT_MIN = -32768;

const int SHRT_MAX = 32767;

const int USHRT_MAX = 65535;

const int INT_MIN = -2147483648;

const int INT_MAX = 2147483647;

const int UINT_MAX = 4294967295;

const int LONG_MIN = -2147483648;

const int LONG_MAX = 2147483647;

const int ULONG_MAX = 4294967295;

const int LLONG_MAX = 9223372036854775807;

const int LLONG_MIN = -9223372036854775808;

const int ULLONG_MAX = -1;

const int _I8_MIN = -128;

const int _I8_MAX = 127;

const int _UI8_MAX = 255;

const int _I16_MIN = -32768;

const int _I16_MAX = 32767;

const int _UI16_MAX = 65535;

const int _I32_MIN = -2147483648;

const int _I32_MAX = 2147483647;

const int _UI32_MAX = 4294967295;

const int _I64_MIN = -9223372036854775808;

const int _I64_MAX = 9223372036854775807;

const int _UI64_MAX = -1;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int EXIT_SUCCESS = 0;

const int EXIT_FAILURE = 1;

const int _WRITE_ABORT_MSG = 1;

const int _CALL_REPORTFAULT = 2;

const int _OUT_TO_DEFAULT = 0;

const int _OUT_TO_STDERR = 1;

const int _OUT_TO_MSGBOX = 2;

const int _REPORT_ERRMODE = 3;

const int RAND_MAX = 32767;

const int _CVTBUFSIZE = 349;

const int _MAX_PATH = 260;

const int _MAX_DRIVE = 3;

const int _MAX_DIR = 256;

const int _MAX_FNAME = 256;

const int _MAX_EXT = 256;

const int _MAX_ENV = 32767;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -2147483648;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 2147483647;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 4294967295;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WCHAR_MIN = 0;

const int WCHAR_MAX = 65535;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;

const String PRId8 = 'hhd';

const String PRId16 = 'hd';

const String PRId32 = 'd';

const String PRId64 = 'lld';

const String PRIdLEAST8 = 'hhd';

const String PRIdLEAST16 = 'hd';

const String PRIdLEAST32 = 'd';

const String PRIdLEAST64 = 'lld';

const String PRIdFAST8 = 'hhd';

const String PRIdFAST16 = 'd';

const String PRIdFAST32 = 'd';

const String PRIdFAST64 = 'lld';

const String PRIdMAX = 'lld';

const String PRIdPTR = 'lld';

const String PRIi8 = 'hhi';

const String PRIi16 = 'hi';

const String PRIi32 = 'i';

const String PRIi64 = 'lli';

const String PRIiLEAST8 = 'hhi';

const String PRIiLEAST16 = 'hi';

const String PRIiLEAST32 = 'i';

const String PRIiLEAST64 = 'lli';

const String PRIiFAST8 = 'hhi';

const String PRIiFAST16 = 'i';

const String PRIiFAST32 = 'i';

const String PRIiFAST64 = 'lli';

const String PRIiMAX = 'lli';

const String PRIiPTR = 'lli';

const String PRIo8 = 'hho';

const String PRIo16 = 'ho';

const String PRIo32 = 'o';

const String PRIo64 = 'llo';

const String PRIoLEAST8 = 'hho';

const String PRIoLEAST16 = 'ho';

const String PRIoLEAST32 = 'o';

const String PRIoLEAST64 = 'llo';

const String PRIoFAST8 = 'hho';

const String PRIoFAST16 = 'o';

const String PRIoFAST32 = 'o';

const String PRIoFAST64 = 'llo';

const String PRIoMAX = 'llo';

const String PRIoPTR = 'llo';

const String PRIu8 = 'hhu';

const String PRIu16 = 'hu';

const String PRIu32 = 'u';

const String PRIu64 = 'llu';

const String PRIuLEAST8 = 'hhu';

const String PRIuLEAST16 = 'hu';

const String PRIuLEAST32 = 'u';

const String PRIuLEAST64 = 'llu';

const String PRIuFAST8 = 'hhu';

const String PRIuFAST16 = 'u';

const String PRIuFAST32 = 'u';

const String PRIuFAST64 = 'llu';

const String PRIuMAX = 'llu';

const String PRIuPTR = 'llu';

const String PRIx8 = 'hhx';

const String PRIx16 = 'hx';

const String PRIx32 = 'x';

const String PRIx64 = 'llx';

const String PRIxLEAST8 = 'hhx';

const String PRIxLEAST16 = 'hx';

const String PRIxLEAST32 = 'x';

const String PRIxLEAST64 = 'llx';

const String PRIxFAST8 = 'hhx';

const String PRIxFAST16 = 'x';

const String PRIxFAST32 = 'x';

const String PRIxFAST64 = 'llx';

const String PRIxMAX = 'llx';

const String PRIxPTR = 'llx';

const String PRIX8 = 'hhX';

const String PRIX16 = 'hX';

const String PRIX32 = 'X';

const String PRIX64 = 'llX';

const String PRIXLEAST8 = 'hhX';

const String PRIXLEAST16 = 'hX';

const String PRIXLEAST32 = 'X';

const String PRIXLEAST64 = 'llX';

const String PRIXFAST8 = 'hhX';

const String PRIXFAST16 = 'X';

const String PRIXFAST32 = 'X';

const String PRIXFAST64 = 'llX';

const String PRIXMAX = 'llX';

const String PRIXPTR = 'llX';

const String SCNd8 = 'hhd';

const String SCNd16 = 'hd';

const String SCNd32 = 'd';

const String SCNd64 = 'lld';

const String SCNdLEAST8 = 'hhd';

const String SCNdLEAST16 = 'hd';

const String SCNdLEAST32 = 'd';

const String SCNdLEAST64 = 'lld';

const String SCNdFAST8 = 'hhd';

const String SCNdFAST16 = 'd';

const String SCNdFAST32 = 'd';

const String SCNdFAST64 = 'lld';

const String SCNdMAX = 'lld';

const String SCNdPTR = 'lld';

const String SCNi8 = 'hhi';

const String SCNi16 = 'hi';

const String SCNi32 = 'i';

const String SCNi64 = 'lli';

const String SCNiLEAST8 = 'hhi';

const String SCNiLEAST16 = 'hi';

const String SCNiLEAST32 = 'i';

const String SCNiLEAST64 = 'lli';

const String SCNiFAST8 = 'hhi';

const String SCNiFAST16 = 'i';

const String SCNiFAST32 = 'i';

const String SCNiFAST64 = 'lli';

const String SCNiMAX = 'lli';

const String SCNiPTR = 'lli';

const String SCNo8 = 'hho';

const String SCNo16 = 'ho';

const String SCNo32 = 'o';

const String SCNo64 = 'llo';

const String SCNoLEAST8 = 'hho';

const String SCNoLEAST16 = 'ho';

const String SCNoLEAST32 = 'o';

const String SCNoLEAST64 = 'llo';

const String SCNoFAST8 = 'hho';

const String SCNoFAST16 = 'o';

const String SCNoFAST32 = 'o';

const String SCNoFAST64 = 'llo';

const String SCNoMAX = 'llo';

const String SCNoPTR = 'llo';

const String SCNu8 = 'hhu';

const String SCNu16 = 'hu';

const String SCNu32 = 'u';

const String SCNu64 = 'llu';

const String SCNuLEAST8 = 'hhu';

const String SCNuLEAST16 = 'hu';

const String SCNuLEAST32 = 'u';

const String SCNuLEAST64 = 'llu';

const String SCNuFAST8 = 'hhu';

const String SCNuFAST16 = 'u';

const String SCNuFAST32 = 'u';

const String SCNuFAST64 = 'llu';

const String SCNuMAX = 'llu';

const String SCNuPTR = 'llu';

const String SCNx8 = 'hhx';

const String SCNx16 = 'hx';

const String SCNx32 = 'x';

const String SCNx64 = 'llx';

const String SCNxLEAST8 = 'hhx';

const String SCNxLEAST16 = 'hx';

const String SCNxLEAST32 = 'x';

const String SCNxLEAST64 = 'llx';

const String SCNxFAST8 = 'hhx';

const String SCNxFAST16 = 'x';

const String SCNxFAST32 = 'x';

const String SCNxFAST64 = 'llx';

const String SCNxMAX = 'llx';

const String SCNxPTR = 'llx';

const int M3_COMPILER_CLANG = 1;

const String M3_COMPILER_VER = 'Clang 21.1.8';

const String M3_ARCH = 'x86_64';
