// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by tool/generate_bindings.dart from SwiftSoupWrapper-Swift.h.
// Re-run: cd packages/swiftsoup && dart run tool/generate_bindings.dart

#include <stdint.h>
#include <stdbool.h>

#import <Foundation/NSObject.h>
#import <Foundation/NSString.h>
#import <Foundation/NSArray.h>

@class NSNumber;

@interface SwiftSoupBridge : NSObject
+ (int32_t)parse:(NSString * _Nonnull)html baseUri:(NSString * _Nonnull)baseUri;
+ (int32_t)parseFragment:(NSString * _Nonnull)html baseUri:(NSString * _Nonnull)baseUri;
+ (int32_t)select:(int32_t)handle selector:(NSString * _Nonnull)selector;
+ (int32_t)selectFirst:(int32_t)handle selector:(NSString * _Nonnull)selector;
+ (NSString * _Nullable)attr:(int32_t)handle key:(NSString * _Nonnull)key;
+ (BOOL)hasAttr:(int32_t)handle key:(NSString * _Nonnull)key;
+ (void)setAttr:(int32_t)handle key:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
+ (void)removeAttr:(int32_t)handle key:(NSString * _Nonnull)key;
+ (NSString * _Nullable)text:(int32_t)handle;
+ (NSString * _Nullable)ownText:(int32_t)handle;
+ (NSString * _Nullable)innerHtml:(int32_t)handle;
+ (NSString * _Nullable)outerHtml:(int32_t)handle;
+ (void)setText:(int32_t)handle text:(NSString * _Nonnull)text;
+ (void)setHtml:(int32_t)handle html:(NSString * _Nonnull)html;
+ (NSString * _Nullable)data:(int32_t)handle;
+ (NSString * _Nullable)tagName:(int32_t)handle;
+ (NSString * _Nullable)elementId:(int32_t)handle;
+ (NSString * _Nullable)className:(int32_t)handle;
+ (BOOL)hasClass:(int32_t)handle name:(NSString * _Nonnull)name;
+ (void)addClass:(int32_t)handle name:(NSString * _Nonnull)name;
+ (void)removeClass:(int32_t)handle name:(NSString * _Nonnull)name;
+ (int32_t)size:(int32_t)handle;
+ (int32_t)get:(int32_t)handle index:(int32_t)index;
+ (int32_t)first:(int32_t)handle;
+ (int32_t)last:(int32_t)handle;
+ (int32_t)parent:(int32_t)handle;
+ (int32_t)children:(int32_t)handle;
+ (int32_t)nextSibling:(int32_t)handle;
+ (int32_t)prevSibling:(int32_t)handle;
+ (int32_t)siblings:(int32_t)handle;
+ (void)remove:(int32_t)handle;
+ (void)prepend:(int32_t)handle html:(NSString * _Nonnull)html;
+ (void)append:(int32_t)handle html:(NSString * _Nonnull)html;
+ (NSString * _Nullable)nodeBaseUri:(int32_t)handle;
+ (NSString * _Nullable)nodeAbsUrl:(int32_t)handle key:(NSString * _Nonnull)key;
+ (void)setNodeBaseUri:(int32_t)handle value:(NSString * _Nonnull)value;
+ (int32_t)createElement:(NSString * _Nonnull)tag;
+ (int32_t)createTextNode:(NSString * _Nonnull)text;
+ (int32_t)createElements:(NSArray<NSNumber *> * _Nonnull)handles;
+ (NSString * _Nullable)nodeName:(int32_t)handle;
+ (int32_t)childNodeSize:(int32_t)handle;
+ (int32_t)childNode:(int32_t)handle index:(int32_t)index;
+ (NSArray<NSNumber *> * _Nonnull)childNodeHandles:(int32_t)handle;
+ (BOOL)isTextNode:(int32_t)handle;
+ (int32_t)parentNode:(int32_t)handle;
+ (NSString * _Nullable)nodeOuterHtml:(int32_t)handle;
+ (void)removeNode:(int32_t)handle;
+ (NSArray<NSNumber *> * _Nonnull)textNodeHandles:(int32_t)handle;
+ (NSString * _Nullable)textNodeText:(int32_t)handle;
+ (void)setTextNodeText:(int32_t)handle text:(NSString * _Nonnull)text;
+ (NSString * _Nullable)textNodeWholeText:(int32_t)handle;
+ (BOOL)textNodeIsBlank:(int32_t)handle;
+ (void)free:(int32_t)handle;
+ (void)releaseAll;
+ (void)dispose;
@end

