import 'package:jsoup/src/jsoup_api.dart';

/// SwiftSoup-backed [NativeHtmlParser] for iOS and macOS.
///
/// Uses the SwiftSoupBridge @objc wrapper (in `swift/Sources/`) which exposes
/// SwiftSoup's API via Objective-C FFI. Dart bindings are generated by
/// swiftgen (or ffigen) — see `swiftgen.yaml` and
/// `tool/generate_swiftsoup_bindings.dart`.
///
/// The bridge uses the same handle-based pattern as `JsoupParser`:
/// - `parse()` returns an opaque int handle
/// - Other methods accept handles to identify elements/node lists
/// - `free()` releases a handle; `dispose()` releases all
///
/// ## Generating Bindings (requires macOS)
///
/// ```bash
/// cd packages/jsoup
/// dart run tool/generate_swiftsoup_bindings.dart
/// ```
///
/// Once bindings are generated to `lib/src/bindings/swiftsoup/`, replace the
/// stub implementations below with calls to the generated
/// `SwiftSoupBridge` class.
class SwiftSoupParser implements NativeHtmlParser {
  /// Creates a SwiftSoup parser.
  ///
  /// Throws [UnimplementedError] until swiftgen bindings are generated.
  SwiftSoupParser() {
    throw UnimplementedError(
      'SwiftSoup parser requires generated bindings. '
      'Run tool/generate_swiftsoup_bindings.dart on macOS first.',
    );
  }

  @override
  String? nodeBaseUri(int handle) => null;

  @override
  String? nodeAbsUrl(int handle, String key) => null;

  @override
  void setNodeBaseUri(int handle, String value) {}

  @override
  int createElement(String tag) => -1;

  @override
  int parse(String html, {String baseUri = ''}) => -1;

  @override
  int parseFragment(String html, {String baseUri = ''}) => -1;

  @override
  int select(int handle, String selector) => -1;

  @override
  int selectFirst(int handle, String selector) => -1;

  @override
  String? attr(int handle, String key) => null;

  @override
  bool hasAttr(int handle, String key) => false;

  @override
  String? text(int handle) => null;

  @override
  String? ownText(int handle) => null;

  @override
  String? innerHtml(int handle) => null;

  @override
  String? outerHtml(int handle) => null;

  @override
  String? tagName(int handle) => null;

  @override
  String? id(int handle) => null;

  @override
  String? className(int handle) => null;

  @override
  bool hasClass(int handle, String name) => false;

  @override
  int size(int handle) => -1;

  @override
  int get(int handle, int index) => -1;

  @override
  int first(int handle) => -1;

  @override
  int last(int handle) => -1;

  @override
  int parent(int handle) => -1;

  @override
  int children(int handle) => -1;

  @override
  int nextSibling(int handle) => -1;

  @override
  int prevSibling(int handle) => -1;

  @override
  int siblings(int handle) => -1;

  @override
  void setText(int handle, String text) {}

  @override
  void setHtml(int handle, String html) {}

  @override
  void remove(int handle) {}

  @override
  void prepend(int handle, String html) {}

  @override
  void append(int handle, String html) {}

  @override
  void setAttr(int handle, String key, String value) {}

  @override
  void removeAttr(int handle, String key) {}

  @override
  void addClass(int handle, String name) {}

  @override
  void removeClass(int handle, String name) {}

  @override
  String? data(int handle) => null;

  @override
  int createTextNode(String text) => -1;

  @override
  int createElements(List<int> elementHandles) => -1;

  @override
  String? nodeName(int handle) => null;

  @override
  int childNodeSize(int handle) => 0;

  @override
  int childNode(int handle, int index) => -1;

  @override
  List<int> childNodeHandles(int handle) => const <int>[];

  @override
  bool isTextNode(int handle) => false;

  @override
  int parentNode(int handle) => -1;

  @override
  String? nodeOuterHtml(int handle) => null;

  @override
  void removeNode(int handle) {}

  @override
  List<int> textNodeHandles(int handle) => const <int>[];

  @override
  String? textNodeText(int handle) => null;

  @override
  void setTextNodeText(int handle, String text) {}

  @override
  String? textNodeWholeText(int handle) => null;

  @override
  bool textNodeIsBlank(int handle) => true;

  @override
  void free(int handle) {}

  @override
  void releaseAll() {}

  @override
  void dispose() {}
}
