// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: always_specify_types
// ignore_for_file: avoid_positional_boolean_parameters
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: unreachable_from_main
// ignore_for_file: unused_element
// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
@ffi.DefaultAsset('package:aidoku_plugin_loader/src/wasm/wasm_bindings_generated.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.UintPtr>()
external int __security_cookie;

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_byte_vec_t>)>()
external void wasm_byte_vec_new_empty(
  ffi.Pointer<wasm_byte_vec_t> out,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_byte_vec_t>, ffi.Size, ffi.Pointer<ffi.Char>)>()
external void wasm_byte_vec_new(
  ffi.Pointer<wasm_byte_vec_t> out,
  int arg1,
  ffi.Pointer<ffi.Char> arg2,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_byte_vec_t>)>()
external void wasm_byte_vec_delete(
  ffi.Pointer<wasm_byte_vec_t> arg0,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_engine_t>)>()
external void wasm_engine_delete(
  ffi.Pointer<wasm_engine_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_engine_t> Function()>()
external ffi.Pointer<wasm_engine_t> wasm_engine_new();

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_store_t>)>()
external void wasm_store_delete(
  ffi.Pointer<wasm_store_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_store_t> Function(ffi.Pointer<wasm_engine_t>)>()
external ffi.Pointer<wasm_store_t> wasm_store_new(
  ffi.Pointer<wasm_engine_t> arg0,
);

@ffi.Native<ffi.Uint32>()
external final int wasm_limits_max_default;

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<wasm_valtype_t>)>()
external int wasm_valtype_kind(
  ffi.Pointer<wasm_valtype_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_valtype_vec_t> Function(ffi.Pointer<wasm_functype_t>)>()
external ffi.Pointer<wasm_valtype_vec_t> wasm_functype_results(
  ffi.Pointer<wasm_functype_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_functype_t> Function(ffi.Pointer<wasm_externtype_t>)>()
external ffi.Pointer<wasm_functype_t> wasm_externtype_as_functype_const(
  ffi.Pointer<wasm_externtype_t> arg0,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_importtype_vec_t>)>()
external void wasm_importtype_vec_new_empty(
  ffi.Pointer<wasm_importtype_vec_t> out,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_importtype_vec_t>)>()
external void wasm_importtype_vec_delete(
  ffi.Pointer<wasm_importtype_vec_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_byte_vec_t> Function(ffi.Pointer<wasm_importtype_t>)>()
external ffi.Pointer<wasm_byte_vec_t> wasm_importtype_module(
  ffi.Pointer<wasm_importtype_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_byte_vec_t> Function(ffi.Pointer<wasm_importtype_t>)>()
external ffi.Pointer<wasm_byte_vec_t> wasm_importtype_name(
  ffi.Pointer<wasm_importtype_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_externtype_t> Function(ffi.Pointer<wasm_importtype_t>)>()
external ffi.Pointer<wasm_externtype_t> wasm_importtype_type(
  ffi.Pointer<wasm_importtype_t> arg0,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_exporttype_vec_t>)>()
external void wasm_exporttype_vec_new_empty(
  ffi.Pointer<wasm_exporttype_vec_t> out,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_exporttype_vec_t>)>()
external void wasm_exporttype_vec_delete(
  ffi.Pointer<wasm_exporttype_vec_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_byte_vec_t> Function(ffi.Pointer<wasm_exporttype_t>)>()
external ffi.Pointer<wasm_byte_vec_t> wasm_exporttype_name(
  ffi.Pointer<wasm_exporttype_t> arg0,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_val_vec_t>)>()
external void wasm_val_vec_new_empty(
  ffi.Pointer<wasm_val_vec_t> out,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_val_vec_t>, ffi.Size)>()
external void wasm_val_vec_new_uninitialized(
  ffi.Pointer<wasm_val_vec_t> out,
  int arg1,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_val_vec_t>)>()
external void wasm_val_vec_delete(
  ffi.Pointer<wasm_val_vec_t> arg0,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_trap_t>)>()
external void wasm_trap_delete(
  ffi.Pointer<wasm_trap_t> arg0,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_trap_t>, ffi.Pointer<wasm_byte_vec_t>)>()
external void wasm_trap_message(
  ffi.Pointer<wasm_trap_t> arg0,
  ffi.Pointer<wasm_byte_vec_t> out,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_module_t>)>()
external void wasm_module_delete(
  ffi.Pointer<wasm_module_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_module_t> Function(ffi.Pointer<wasm_store_t>, ffi.Pointer<wasm_byte_vec_t>)>()
external ffi.Pointer<wasm_module_t> wasm_module_new(
  ffi.Pointer<wasm_store_t> arg0,
  ffi.Pointer<wasm_byte_vec_t> binary,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_module_t>, ffi.Pointer<wasm_importtype_vec_t>)>()
external void wasm_module_imports(
  ffi.Pointer<wasm_module_t> arg0,
  ffi.Pointer<wasm_importtype_vec_t> out,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_module_t>, ffi.Pointer<wasm_exporttype_vec_t>)>()
external void wasm_module_exports(
  ffi.Pointer<wasm_module_t> arg0,
  ffi.Pointer<wasm_exporttype_vec_t> out,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_func_t>)>()
external void wasm_func_delete(
  ffi.Pointer<wasm_func_t> arg0,
);

@ffi.Native<
  ffi.Pointer<wasm_func_t> Function(ffi.Pointer<wasm_store_t>, ffi.Pointer<wasm_functype_t>, wasm_func_callback_t)
>()
external ffi.Pointer<wasm_func_t> wasm_func_new(
  ffi.Pointer<wasm_store_t> arg0,
  ffi.Pointer<wasm_functype_t> arg1,
  wasm_func_callback_t arg2,
);

@ffi.Native<
  ffi.Pointer<wasm_trap_t> Function(ffi.Pointer<wasm_func_t>, ffi.Pointer<wasm_val_vec_t>, ffi.Pointer<wasm_val_vec_t>)
>()
external ffi.Pointer<wasm_trap_t> wasm_func_call(
  ffi.Pointer<wasm_func_t> arg0,
  ffi.Pointer<wasm_val_vec_t> args,
  ffi.Pointer<wasm_val_vec_t> results,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_memory_t>)>()
external void wasm_memory_delete(
  ffi.Pointer<wasm_memory_t> arg0,
);

@ffi.Native<ffi.Size>()
external final int MEMORY_PAGE_SIZE;

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<wasm_memory_t>)>()
external ffi.Pointer<ffi.Char> wasm_memory_data(
  ffi.Pointer<wasm_memory_t> arg0,
);

@ffi.Native<ffi.Size Function(ffi.Pointer<wasm_memory_t>)>()
external int wasm_memory_data_size(
  ffi.Pointer<wasm_memory_t> arg0,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_extern_vec_t>)>()
external void wasm_extern_vec_new_empty(
  ffi.Pointer<wasm_extern_vec_t> out,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_extern_vec_t>, ffi.Size, ffi.Pointer<ffi.Pointer<wasm_extern_t>>)>()
external void wasm_extern_vec_new(
  ffi.Pointer<wasm_extern_vec_t> out,
  int arg1,
  ffi.Pointer<ffi.Pointer<wasm_extern_t>> arg2,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_extern_vec_t>)>()
external void wasm_extern_vec_delete(
  ffi.Pointer<wasm_extern_vec_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_extern_t> Function(ffi.Pointer<wasm_func_t>)>()
external ffi.Pointer<wasm_extern_t> wasm_func_as_extern(
  ffi.Pointer<wasm_func_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_func_t> Function(ffi.Pointer<wasm_extern_t>)>()
external ffi.Pointer<wasm_func_t> wasm_extern_as_func(
  ffi.Pointer<wasm_extern_t> arg0,
);

@ffi.Native<ffi.Pointer<wasm_memory_t> Function(ffi.Pointer<wasm_extern_t>)>()
external ffi.Pointer<wasm_memory_t> wasm_extern_as_memory(
  ffi.Pointer<wasm_extern_t> arg0,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_instance_t>)>()
external void wasm_instance_delete(
  ffi.Pointer<wasm_instance_t> arg0,
);

@ffi.Native<
  ffi.Pointer<wasm_instance_t> Function(
    ffi.Pointer<wasm_store_t>,
    ffi.Pointer<wasm_module_t>,
    ffi.Pointer<wasm_extern_vec_t>,
    ffi.Pointer<ffi.Pointer<wasm_trap_t>>,
  )
>()
external ffi.Pointer<wasm_instance_t> wasm_instance_new(
  ffi.Pointer<wasm_store_t> arg0,
  ffi.Pointer<wasm_module_t> arg1,
  ffi.Pointer<wasm_extern_vec_t> imports,
  ffi.Pointer<ffi.Pointer<wasm_trap_t>> arg3,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<wasm_instance_t>, ffi.Pointer<wasm_extern_vec_t>)>()
external void wasm_instance_exports(
  ffi.Pointer<wasm_instance_t> arg0,
  ffi.Pointer<wasm_extern_vec_t> out,
);

final class wasm_byte_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Char> data;
}

final class wasm_engine_t extends ffi.Opaque {}

final class wasm_store_t extends ffi.Opaque {}

enum wasm_mutability_enum {
  WASM_CONST(0),
  WASM_VAR(1)
  ;

  final int value;
  const wasm_mutability_enum(this.value);

  static wasm_mutability_enum fromValue(int value) => switch (value) {
    0 => WASM_CONST,
    1 => WASM_VAR,
    _ => throw ArgumentError('Unknown value for wasm_mutability_enum: $value'),
  };
}

final class wasm_valtype_t extends ffi.Opaque {}

final class wasm_valtype_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Pointer<wasm_valtype_t>> data;
}

enum wasm_valkind_enum {
  WASM_I32(0),
  WASM_I64(1),
  WASM_F32(2),
  WASM_F64(3),
  WASM_EXTERNREF(128),
  WASM_FUNCREF(129)
  ;

  final int value;
  const wasm_valkind_enum(this.value);

  static wasm_valkind_enum fromValue(int value) => switch (value) {
    0 => WASM_I32,
    1 => WASM_I64,
    2 => WASM_F32,
    3 => WASM_F64,
    128 => WASM_EXTERNREF,
    129 => WASM_FUNCREF,
    _ => throw ArgumentError('Unknown value for wasm_valkind_enum: $value'),
  };
}

final class wasm_functype_t extends ffi.Opaque {}

final class wasm_externtype_t extends ffi.Opaque {}

enum wasm_externkind_enum {
  WASM_EXTERN_FUNC(0),
  WASM_EXTERN_GLOBAL(1),
  WASM_EXTERN_TABLE(2),
  WASM_EXTERN_MEMORY(3)
  ;

  final int value;
  const wasm_externkind_enum(this.value);

  static wasm_externkind_enum fromValue(int value) => switch (value) {
    0 => WASM_EXTERN_FUNC,
    1 => WASM_EXTERN_GLOBAL,
    2 => WASM_EXTERN_TABLE,
    3 => WASM_EXTERN_MEMORY,
    _ => throw ArgumentError('Unknown value for wasm_externkind_enum: $value'),
  };
}

final class wasm_importtype_t extends ffi.Opaque {}

final class wasm_importtype_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Pointer<wasm_importtype_t>> data;
}

final class wasm_exporttype_t extends ffi.Opaque {}

final class wasm_exporttype_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Pointer<wasm_exporttype_t>> data;
}

/// ////////////////////////////////////////////////////////////////////////////
final class wasm_ref_t extends ffi.Opaque {}

final class UnnamedUnion extends ffi.Union {
  @ffi.Int32()
  external int i32;

  @ffi.Int64()
  external int i64;

  @ffi.Float()
  external double f32;

  @ffi.Double()
  external double f64;

  external ffi.Pointer<wasm_ref_t> ref;
}

final class wasm_val_t extends ffi.Struct {
  @ffi.Uint8()
  external int kind;

  external UnnamedUnion of;
}

final class wasm_val_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<wasm_val_t> data;
}

final class wasm_instance_t extends ffi.Opaque {}

final class wasm_trap_t extends ffi.Opaque {}

final class wasm_module_t extends ffi.Opaque {}

final class wasm_func_t extends ffi.Opaque {}

typedef wasm_func_callback_t =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<wasm_trap_t> Function(ffi.Pointer<wasm_val_vec_t> args, ffi.Pointer<wasm_val_vec_t> results)
      >
    >;

final class wasm_memory_t extends ffi.Opaque {}

final class wasm_extern_t extends ffi.Opaque {}

final class wasm_extern_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Pointer<wasm_extern_t>> data;
}

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int _WCHAR_T_DEFINED = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_CXX23 = 0;

const int _HAS_CXX26 = 0;

const int _HAS_NODISCARD = 1;

const int _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE = 1;

const int _CRT_BUILD_DESKTOP_APP = 1;

const int _UCRT_DISABLED_WARNINGS = 4324;

const int _ARGMAX = 100;

const int _TRUNCATE = -1;

const int _CRT_INT_MAX = 2147483647;

const int _CRT_SIZE_MAX = -1;

const String __FILEW__ = 'C';

const int _CRT_FUNCTIONS_REQUIRED = 1;

const int _CRT_HAS_CXX17 = 0;

const int _CRT_HAS_C11 = 0;

const int _CRT_INTERNAL_NONSTDC_NAMES = 1;

const int __STDC_SECURE_LIB__ = 200411;

const int __GOT_SECURE_LIB__ = 200411;

const int __STDC_WANT_SECURE_LIB__ = 1;

const int _SECURECRT_FILL_BUFFER_PATTERN = 254;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = 0;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES = 1;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY = 0;

const int _STATIC_INLINE_UCRT_FUNCTIONS = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -2147483648;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 2147483647;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 4294967295;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WCHAR_MIN = 0;

const int WCHAR_MAX = 65535;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;

const int __bool_true_false_are_defined = 1;

const int false$ = 0;

const int true$ = 1;

const int EPERM = 1;

const int ENOENT = 2;

const int ESRCH = 3;

const int EINTR = 4;

const int EIO = 5;

const int ENXIO = 6;

const int E2BIG = 7;

const int ENOEXEC = 8;

const int EBADF = 9;

const int ECHILD = 10;

const int EAGAIN = 11;

const int ENOMEM = 12;

const int EACCES = 13;

const int EFAULT = 14;

const int EBUSY = 16;

const int EEXIST = 17;

const int EXDEV = 18;

const int ENODEV = 19;

const int ENOTDIR = 20;

const int EISDIR = 21;

const int ENFILE = 23;

const int EMFILE = 24;

const int ENOTTY = 25;

const int EFBIG = 27;

const int ENOSPC = 28;

const int ESPIPE = 29;

const int EROFS = 30;

const int EMLINK = 31;

const int EPIPE = 32;

const int EDOM = 33;

const int EDEADLK = 36;

const int ENAMETOOLONG = 38;

const int ENOLCK = 39;

const int ENOSYS = 40;

const int ENOTEMPTY = 41;

const int EINVAL = 22;

const int ERANGE = 34;

const int EILSEQ = 42;

const int STRUNCATE = 80;

const int EDEADLOCK = 36;

const int EADDRINUSE = 100;

const int EADDRNOTAVAIL = 101;

const int EAFNOSUPPORT = 102;

const int EALREADY = 103;

const int EBADMSG = 104;

const int ECANCELED = 105;

const int ECONNABORTED = 106;

const int ECONNREFUSED = 107;

const int ECONNRESET = 108;

const int EDESTADDRREQ = 109;

const int EHOSTUNREACH = 110;

const int EIDRM = 111;

const int EINPROGRESS = 112;

const int EISCONN = 113;

const int ELOOP = 114;

const int EMSGSIZE = 115;

const int ENETDOWN = 116;

const int ENETRESET = 117;

const int ENETUNREACH = 118;

const int ENOBUFS = 119;

const int ENODATA = 120;

const int ENOLINK = 121;

const int ENOMSG = 122;

const int ENOPROTOOPT = 123;

const int ENOSR = 124;

const int ENOSTR = 125;

const int ENOTCONN = 126;

const int ENOTRECOVERABLE = 127;

const int ENOTSOCK = 128;

const int ENOTSUP = 129;

const int EOPNOTSUPP = 130;

const int EOTHER = 131;

const int EOVERFLOW = 132;

const int EOWNERDEAD = 133;

const int EPROTO = 134;

const int EPROTONOSUPPORT = 135;

const int EPROTOTYPE = 136;

const int ETIME = 137;

const int ETIMEDOUT = 138;

const int ETXTBSY = 139;

const int EWOULDBLOCK = 140;

const int _NLSCMPERROR = 2147483647;
