// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: always_specify_types
// ignore_for_file: avoid_positional_boolean_parameters
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: unreachable_from_main
// ignore_for_file: unused_element
// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// Auto-generated bindings for the WebAssembly C API (wasm.h). Run: dart run ffigen --config ffigen.yaml Do not edit by hand — edit ffigen.yaml and regenerate.
///
class NativeWasmerBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeWasmerBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeWasmerBindings.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
    : _lookup = lookup;

  late final ffi.Pointer<ffi.UintPtr> ___security_cookie = _lookup<ffi.UintPtr>('__security_cookie');

  int get __security_cookie => ___security_cookie.value;

  set __security_cookie(int value) => ___security_cookie.value = value;

  void wasm_byte_vec_new_empty(
    ffi.Pointer<wasm_byte_vec_t> out,
  ) {
    return _wasm_byte_vec_new_empty(
      out,
    );
  }

  late final _wasm_byte_vec_new_emptyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_byte_vec_t>)>>(
    'wasm_byte_vec_new_empty',
  );
  late final _wasm_byte_vec_new_empty = _wasm_byte_vec_new_emptyPtr
      .asFunction<void Function(ffi.Pointer<wasm_byte_vec_t>)>();

  void wasm_byte_vec_new(
    ffi.Pointer<wasm_byte_vec_t> out,
    int arg1,
    ffi.Pointer<ffi.Char> arg2,
  ) {
    return _wasm_byte_vec_new(
      out,
      arg1,
      arg2,
    );
  }

  late final _wasm_byte_vec_newPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_byte_vec_t>, ffi.Size, ffi.Pointer<ffi.Char>)>>(
        'wasm_byte_vec_new',
      );
  late final _wasm_byte_vec_new = _wasm_byte_vec_newPtr
      .asFunction<void Function(ffi.Pointer<wasm_byte_vec_t>, int, ffi.Pointer<ffi.Char>)>();

  void wasm_byte_vec_delete(
    ffi.Pointer<wasm_byte_vec_t> arg0,
  ) {
    return _wasm_byte_vec_delete(
      arg0,
    );
  }

  late final _wasm_byte_vec_deletePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_byte_vec_t>)>>(
    'wasm_byte_vec_delete',
  );
  late final _wasm_byte_vec_delete = _wasm_byte_vec_deletePtr.asFunction<void Function(ffi.Pointer<wasm_byte_vec_t>)>();

  void wasm_engine_delete(
    ffi.Pointer<wasm_engine_t> arg0,
  ) {
    return _wasm_engine_delete(
      arg0,
    );
  }

  late final _wasm_engine_deletePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_engine_t>)>>(
    'wasm_engine_delete',
  );
  late final _wasm_engine_delete = _wasm_engine_deletePtr.asFunction<void Function(ffi.Pointer<wasm_engine_t>)>();

  ffi.Pointer<wasm_engine_t> wasm_engine_new() {
    return _wasm_engine_new();
  }

  late final _wasm_engine_newPtr = _lookup<ffi.NativeFunction<ffi.Pointer<wasm_engine_t> Function()>>(
    'wasm_engine_new',
  );
  late final _wasm_engine_new = _wasm_engine_newPtr.asFunction<ffi.Pointer<wasm_engine_t> Function()>();

  void wasm_store_delete(
    ffi.Pointer<wasm_store_t> arg0,
  ) {
    return _wasm_store_delete(
      arg0,
    );
  }

  late final _wasm_store_deletePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_store_t>)>>(
    'wasm_store_delete',
  );
  late final _wasm_store_delete = _wasm_store_deletePtr.asFunction<void Function(ffi.Pointer<wasm_store_t>)>();

  ffi.Pointer<wasm_store_t> wasm_store_new(
    ffi.Pointer<wasm_engine_t> arg0,
  ) {
    return _wasm_store_new(
      arg0,
    );
  }

  late final _wasm_store_newPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wasm_store_t> Function(ffi.Pointer<wasm_engine_t>)>>('wasm_store_new');
  late final _wasm_store_new = _wasm_store_newPtr
      .asFunction<ffi.Pointer<wasm_store_t> Function(ffi.Pointer<wasm_engine_t>)>();

  late final ffi.Pointer<ffi.Uint32> _wasm_limits_max_default = _lookup<ffi.Uint32>('wasm_limits_max_default');

  int get wasm_limits_max_default => _wasm_limits_max_default.value;

  ffi.Pointer<wasm_functype_t> wasm_externtype_as_functype_const(
    ffi.Pointer<wasm_externtype_t> arg0,
  ) {
    return _wasm_externtype_as_functype_const(
      arg0,
    );
  }

  late final _wasm_externtype_as_functype_constPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wasm_functype_t> Function(ffi.Pointer<wasm_externtype_t>)>>(
        'wasm_externtype_as_functype_const',
      );
  late final _wasm_externtype_as_functype_const = _wasm_externtype_as_functype_constPtr
      .asFunction<ffi.Pointer<wasm_functype_t> Function(ffi.Pointer<wasm_externtype_t>)>();

  void wasm_importtype_vec_new_empty(
    ffi.Pointer<wasm_importtype_vec_t> out,
  ) {
    return _wasm_importtype_vec_new_empty(
      out,
    );
  }

  late final _wasm_importtype_vec_new_emptyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_importtype_vec_t>)>>(
        'wasm_importtype_vec_new_empty',
      );
  late final _wasm_importtype_vec_new_empty = _wasm_importtype_vec_new_emptyPtr
      .asFunction<void Function(ffi.Pointer<wasm_importtype_vec_t>)>();

  void wasm_importtype_vec_delete(
    ffi.Pointer<wasm_importtype_vec_t> arg0,
  ) {
    return _wasm_importtype_vec_delete(
      arg0,
    );
  }

  late final _wasm_importtype_vec_deletePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_importtype_vec_t>)>>('wasm_importtype_vec_delete');
  late final _wasm_importtype_vec_delete = _wasm_importtype_vec_deletePtr
      .asFunction<void Function(ffi.Pointer<wasm_importtype_vec_t>)>();

  ffi.Pointer<wasm_byte_vec_t> wasm_importtype_module(
    ffi.Pointer<wasm_importtype_t> arg0,
  ) {
    return _wasm_importtype_module(
      arg0,
    );
  }

  late final _wasm_importtype_modulePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wasm_byte_vec_t> Function(ffi.Pointer<wasm_importtype_t>)>>(
        'wasm_importtype_module',
      );
  late final _wasm_importtype_module = _wasm_importtype_modulePtr
      .asFunction<ffi.Pointer<wasm_byte_vec_t> Function(ffi.Pointer<wasm_importtype_t>)>();

  ffi.Pointer<wasm_byte_vec_t> wasm_importtype_name(
    ffi.Pointer<wasm_importtype_t> arg0,
  ) {
    return _wasm_importtype_name(
      arg0,
    );
  }

  late final _wasm_importtype_namePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wasm_byte_vec_t> Function(ffi.Pointer<wasm_importtype_t>)>>(
        'wasm_importtype_name',
      );
  late final _wasm_importtype_name = _wasm_importtype_namePtr
      .asFunction<ffi.Pointer<wasm_byte_vec_t> Function(ffi.Pointer<wasm_importtype_t>)>();

  ffi.Pointer<wasm_externtype_t> wasm_importtype_type(
    ffi.Pointer<wasm_importtype_t> arg0,
  ) {
    return _wasm_importtype_type(
      arg0,
    );
  }

  late final _wasm_importtype_typePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wasm_externtype_t> Function(ffi.Pointer<wasm_importtype_t>)>>(
        'wasm_importtype_type',
      );
  late final _wasm_importtype_type = _wasm_importtype_typePtr
      .asFunction<ffi.Pointer<wasm_externtype_t> Function(ffi.Pointer<wasm_importtype_t>)>();

  void wasm_exporttype_vec_new_empty(
    ffi.Pointer<wasm_exporttype_vec_t> out,
  ) {
    return _wasm_exporttype_vec_new_empty(
      out,
    );
  }

  late final _wasm_exporttype_vec_new_emptyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_exporttype_vec_t>)>>(
        'wasm_exporttype_vec_new_empty',
      );
  late final _wasm_exporttype_vec_new_empty = _wasm_exporttype_vec_new_emptyPtr
      .asFunction<void Function(ffi.Pointer<wasm_exporttype_vec_t>)>();

  void wasm_exporttype_vec_delete(
    ffi.Pointer<wasm_exporttype_vec_t> arg0,
  ) {
    return _wasm_exporttype_vec_delete(
      arg0,
    );
  }

  late final _wasm_exporttype_vec_deletePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_exporttype_vec_t>)>>('wasm_exporttype_vec_delete');
  late final _wasm_exporttype_vec_delete = _wasm_exporttype_vec_deletePtr
      .asFunction<void Function(ffi.Pointer<wasm_exporttype_vec_t>)>();

  ffi.Pointer<wasm_byte_vec_t> wasm_exporttype_name(
    ffi.Pointer<wasm_exporttype_t> arg0,
  ) {
    return _wasm_exporttype_name(
      arg0,
    );
  }

  late final _wasm_exporttype_namePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wasm_byte_vec_t> Function(ffi.Pointer<wasm_exporttype_t>)>>(
        'wasm_exporttype_name',
      );
  late final _wasm_exporttype_name = _wasm_exporttype_namePtr
      .asFunction<ffi.Pointer<wasm_byte_vec_t> Function(ffi.Pointer<wasm_exporttype_t>)>();

  void wasm_val_vec_new_empty(
    ffi.Pointer<wasm_val_vec_t> out,
  ) {
    return _wasm_val_vec_new_empty(
      out,
    );
  }

  late final _wasm_val_vec_new_emptyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_val_vec_t>)>>(
    'wasm_val_vec_new_empty',
  );
  late final _wasm_val_vec_new_empty = _wasm_val_vec_new_emptyPtr
      .asFunction<void Function(ffi.Pointer<wasm_val_vec_t>)>();

  void wasm_val_vec_new_uninitialized(
    ffi.Pointer<wasm_val_vec_t> out,
    int arg1,
  ) {
    return _wasm_val_vec_new_uninitialized(
      out,
      arg1,
    );
  }

  late final _wasm_val_vec_new_uninitializedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_val_vec_t>, ffi.Size)>>(
        'wasm_val_vec_new_uninitialized',
      );
  late final _wasm_val_vec_new_uninitialized = _wasm_val_vec_new_uninitializedPtr
      .asFunction<void Function(ffi.Pointer<wasm_val_vec_t>, int)>();

  void wasm_val_vec_delete(
    ffi.Pointer<wasm_val_vec_t> arg0,
  ) {
    return _wasm_val_vec_delete(
      arg0,
    );
  }

  late final _wasm_val_vec_deletePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_val_vec_t>)>>(
    'wasm_val_vec_delete',
  );
  late final _wasm_val_vec_delete = _wasm_val_vec_deletePtr.asFunction<void Function(ffi.Pointer<wasm_val_vec_t>)>();

  void wasm_trap_delete(
    ffi.Pointer<wasm_trap_t> arg0,
  ) {
    return _wasm_trap_delete(
      arg0,
    );
  }

  late final _wasm_trap_deletePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_trap_t>)>>(
    'wasm_trap_delete',
  );
  late final _wasm_trap_delete = _wasm_trap_deletePtr.asFunction<void Function(ffi.Pointer<wasm_trap_t>)>();

  void wasm_trap_message(
    ffi.Pointer<wasm_trap_t> arg0,
    ffi.Pointer<wasm_byte_vec_t> out,
  ) {
    return _wasm_trap_message(
      arg0,
      out,
    );
  }

  late final _wasm_trap_messagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_trap_t>, ffi.Pointer<wasm_byte_vec_t>)>>(
        'wasm_trap_message',
      );
  late final _wasm_trap_message = _wasm_trap_messagePtr
      .asFunction<void Function(ffi.Pointer<wasm_trap_t>, ffi.Pointer<wasm_byte_vec_t>)>();

  void wasm_module_delete(
    ffi.Pointer<wasm_module_t> arg0,
  ) {
    return _wasm_module_delete(
      arg0,
    );
  }

  late final _wasm_module_deletePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_module_t>)>>(
    'wasm_module_delete',
  );
  late final _wasm_module_delete = _wasm_module_deletePtr.asFunction<void Function(ffi.Pointer<wasm_module_t>)>();

  ffi.Pointer<wasm_module_t> wasm_module_new(
    ffi.Pointer<wasm_store_t> arg0,
    ffi.Pointer<wasm_byte_vec_t> binary,
  ) {
    return _wasm_module_new(
      arg0,
      binary,
    );
  }

  late final _wasm_module_newPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wasm_module_t> Function(ffi.Pointer<wasm_store_t>, ffi.Pointer<wasm_byte_vec_t>)>
      >('wasm_module_new');
  late final _wasm_module_new = _wasm_module_newPtr
      .asFunction<ffi.Pointer<wasm_module_t> Function(ffi.Pointer<wasm_store_t>, ffi.Pointer<wasm_byte_vec_t>)>();

  void wasm_module_imports(
    ffi.Pointer<wasm_module_t> arg0,
    ffi.Pointer<wasm_importtype_vec_t> out,
  ) {
    return _wasm_module_imports(
      arg0,
      out,
    );
  }

  late final _wasm_module_importsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_module_t>, ffi.Pointer<wasm_importtype_vec_t>)>>(
        'wasm_module_imports',
      );
  late final _wasm_module_imports = _wasm_module_importsPtr
      .asFunction<void Function(ffi.Pointer<wasm_module_t>, ffi.Pointer<wasm_importtype_vec_t>)>();

  void wasm_module_exports(
    ffi.Pointer<wasm_module_t> arg0,
    ffi.Pointer<wasm_exporttype_vec_t> out,
  ) {
    return _wasm_module_exports(
      arg0,
      out,
    );
  }

  late final _wasm_module_exportsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_module_t>, ffi.Pointer<wasm_exporttype_vec_t>)>>(
        'wasm_module_exports',
      );
  late final _wasm_module_exports = _wasm_module_exportsPtr
      .asFunction<void Function(ffi.Pointer<wasm_module_t>, ffi.Pointer<wasm_exporttype_vec_t>)>();

  void wasm_func_delete(
    ffi.Pointer<wasm_func_t> arg0,
  ) {
    return _wasm_func_delete(
      arg0,
    );
  }

  late final _wasm_func_deletePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_func_t>)>>(
    'wasm_func_delete',
  );
  late final _wasm_func_delete = _wasm_func_deletePtr.asFunction<void Function(ffi.Pointer<wasm_func_t>)>();

  ffi.Pointer<wasm_func_t> wasm_func_new(
    ffi.Pointer<wasm_store_t> arg0,
    ffi.Pointer<wasm_functype_t> arg1,
    wasm_func_callback_t arg2,
  ) {
    return _wasm_func_new(
      arg0,
      arg1,
      arg2,
    );
  }

  late final _wasm_func_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wasm_func_t> Function(
            ffi.Pointer<wasm_store_t>,
            ffi.Pointer<wasm_functype_t>,
            wasm_func_callback_t,
          )
        >
      >('wasm_func_new');
  late final _wasm_func_new = _wasm_func_newPtr
      .asFunction<
        ffi.Pointer<wasm_func_t> Function(ffi.Pointer<wasm_store_t>, ffi.Pointer<wasm_functype_t>, wasm_func_callback_t)
      >();

  ffi.Pointer<wasm_trap_t> wasm_func_call(
    ffi.Pointer<wasm_func_t> arg0,
    ffi.Pointer<wasm_val_vec_t> args,
    ffi.Pointer<wasm_val_vec_t> results,
  ) {
    return _wasm_func_call(
      arg0,
      args,
      results,
    );
  }

  late final _wasm_func_callPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wasm_trap_t> Function(
            ffi.Pointer<wasm_func_t>,
            ffi.Pointer<wasm_val_vec_t>,
            ffi.Pointer<wasm_val_vec_t>,
          )
        >
      >('wasm_func_call');
  late final _wasm_func_call = _wasm_func_callPtr
      .asFunction<
        ffi.Pointer<wasm_trap_t> Function(
          ffi.Pointer<wasm_func_t>,
          ffi.Pointer<wasm_val_vec_t>,
          ffi.Pointer<wasm_val_vec_t>,
        )
      >();

  void wasm_memory_delete(
    ffi.Pointer<wasm_memory_t> arg0,
  ) {
    return _wasm_memory_delete(
      arg0,
    );
  }

  late final _wasm_memory_deletePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_memory_t>)>>(
    'wasm_memory_delete',
  );
  late final _wasm_memory_delete = _wasm_memory_deletePtr.asFunction<void Function(ffi.Pointer<wasm_memory_t>)>();

  late final ffi.Pointer<ffi.Size> _MEMORY_PAGE_SIZE = _lookup<ffi.Size>('MEMORY_PAGE_SIZE');

  int get MEMORY_PAGE_SIZE => _MEMORY_PAGE_SIZE.value;

  ffi.Pointer<ffi.Char> wasm_memory_data(
    ffi.Pointer<wasm_memory_t> arg0,
  ) {
    return _wasm_memory_data(
      arg0,
    );
  }

  late final _wasm_memory_dataPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<wasm_memory_t>)>>('wasm_memory_data');
  late final _wasm_memory_data = _wasm_memory_dataPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<wasm_memory_t>)>();

  int wasm_memory_data_size(
    ffi.Pointer<wasm_memory_t> arg0,
  ) {
    return _wasm_memory_data_size(
      arg0,
    );
  }

  late final _wasm_memory_data_sizePtr = _lookup<ffi.NativeFunction<ffi.Size Function(ffi.Pointer<wasm_memory_t>)>>(
    'wasm_memory_data_size',
  );
  late final _wasm_memory_data_size = _wasm_memory_data_sizePtr.asFunction<int Function(ffi.Pointer<wasm_memory_t>)>();

  void wasm_extern_vec_new_empty(
    ffi.Pointer<wasm_extern_vec_t> out,
  ) {
    return _wasm_extern_vec_new_empty(
      out,
    );
  }

  late final _wasm_extern_vec_new_emptyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_extern_vec_t>)>>('wasm_extern_vec_new_empty');
  late final _wasm_extern_vec_new_empty = _wasm_extern_vec_new_emptyPtr
      .asFunction<void Function(ffi.Pointer<wasm_extern_vec_t>)>();

  void wasm_extern_vec_new(
    ffi.Pointer<wasm_extern_vec_t> out,
    int arg1,
    ffi.Pointer<ffi.Pointer<wasm_extern_t>> arg2,
  ) {
    return _wasm_extern_vec_new(
      out,
      arg1,
      arg2,
    );
  }

  late final _wasm_extern_vec_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<wasm_extern_vec_t>, ffi.Size, ffi.Pointer<ffi.Pointer<wasm_extern_t>>)
        >
      >('wasm_extern_vec_new');
  late final _wasm_extern_vec_new = _wasm_extern_vec_newPtr
      .asFunction<void Function(ffi.Pointer<wasm_extern_vec_t>, int, ffi.Pointer<ffi.Pointer<wasm_extern_t>>)>();

  void wasm_extern_vec_delete(
    ffi.Pointer<wasm_extern_vec_t> arg0,
  ) {
    return _wasm_extern_vec_delete(
      arg0,
    );
  }

  late final _wasm_extern_vec_deletePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_extern_vec_t>)>>('wasm_extern_vec_delete');
  late final _wasm_extern_vec_delete = _wasm_extern_vec_deletePtr
      .asFunction<void Function(ffi.Pointer<wasm_extern_vec_t>)>();

  ffi.Pointer<wasm_extern_t> wasm_func_as_extern(
    ffi.Pointer<wasm_func_t> arg0,
  ) {
    return _wasm_func_as_extern(
      arg0,
    );
  }

  late final _wasm_func_as_externPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wasm_extern_t> Function(ffi.Pointer<wasm_func_t>)>>('wasm_func_as_extern');
  late final _wasm_func_as_extern = _wasm_func_as_externPtr
      .asFunction<ffi.Pointer<wasm_extern_t> Function(ffi.Pointer<wasm_func_t>)>();

  ffi.Pointer<wasm_func_t> wasm_extern_as_func(
    ffi.Pointer<wasm_extern_t> arg0,
  ) {
    return _wasm_extern_as_func(
      arg0,
    );
  }

  late final _wasm_extern_as_funcPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wasm_func_t> Function(ffi.Pointer<wasm_extern_t>)>>('wasm_extern_as_func');
  late final _wasm_extern_as_func = _wasm_extern_as_funcPtr
      .asFunction<ffi.Pointer<wasm_func_t> Function(ffi.Pointer<wasm_extern_t>)>();

  ffi.Pointer<wasm_memory_t> wasm_extern_as_memory(
    ffi.Pointer<wasm_extern_t> arg0,
  ) {
    return _wasm_extern_as_memory(
      arg0,
    );
  }

  late final _wasm_extern_as_memoryPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wasm_memory_t> Function(ffi.Pointer<wasm_extern_t>)>>(
        'wasm_extern_as_memory',
      );
  late final _wasm_extern_as_memory = _wasm_extern_as_memoryPtr
      .asFunction<ffi.Pointer<wasm_memory_t> Function(ffi.Pointer<wasm_extern_t>)>();

  void wasm_instance_delete(
    ffi.Pointer<wasm_instance_t> arg0,
  ) {
    return _wasm_instance_delete(
      arg0,
    );
  }

  late final _wasm_instance_deletePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_instance_t>)>>(
    'wasm_instance_delete',
  );
  late final _wasm_instance_delete = _wasm_instance_deletePtr.asFunction<void Function(ffi.Pointer<wasm_instance_t>)>();

  ffi.Pointer<wasm_instance_t> wasm_instance_new(
    ffi.Pointer<wasm_store_t> arg0,
    ffi.Pointer<wasm_module_t> arg1,
    ffi.Pointer<wasm_extern_vec_t> imports,
    ffi.Pointer<ffi.Pointer<wasm_trap_t>> arg3,
  ) {
    return _wasm_instance_new(
      arg0,
      arg1,
      imports,
      arg3,
    );
  }

  late final _wasm_instance_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wasm_instance_t> Function(
            ffi.Pointer<wasm_store_t>,
            ffi.Pointer<wasm_module_t>,
            ffi.Pointer<wasm_extern_vec_t>,
            ffi.Pointer<ffi.Pointer<wasm_trap_t>>,
          )
        >
      >('wasm_instance_new');
  late final _wasm_instance_new = _wasm_instance_newPtr
      .asFunction<
        ffi.Pointer<wasm_instance_t> Function(
          ffi.Pointer<wasm_store_t>,
          ffi.Pointer<wasm_module_t>,
          ffi.Pointer<wasm_extern_vec_t>,
          ffi.Pointer<ffi.Pointer<wasm_trap_t>>,
        )
      >();

  void wasm_instance_exports(
    ffi.Pointer<wasm_instance_t> arg0,
    ffi.Pointer<wasm_extern_vec_t> out,
  ) {
    return _wasm_instance_exports(
      arg0,
      out,
    );
  }

  late final _wasm_instance_exportsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<wasm_instance_t>, ffi.Pointer<wasm_extern_vec_t>)>>(
        'wasm_instance_exports',
      );
  late final _wasm_instance_exports = _wasm_instance_exportsPtr
      .asFunction<void Function(ffi.Pointer<wasm_instance_t>, ffi.Pointer<wasm_extern_vec_t>)>();
}

final class wasm_byte_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Char> data;
}

final class wasm_engine_t extends ffi.Opaque {}

final class wasm_store_t extends ffi.Opaque {}

enum wasm_mutability_enum {
  WASM_CONST(0),
  WASM_VAR(1)
  ;

  final int value;
  const wasm_mutability_enum(this.value);

  static wasm_mutability_enum fromValue(int value) => switch (value) {
    0 => WASM_CONST,
    1 => WASM_VAR,
    _ => throw ArgumentError('Unknown value for wasm_mutability_enum: $value'),
  };
}

enum wasm_valkind_enum {
  WASM_I32(0),
  WASM_I64(1),
  WASM_F32(2),
  WASM_F64(3),
  WASM_EXTERNREF(128),
  WASM_FUNCREF(129)
  ;

  final int value;
  const wasm_valkind_enum(this.value);

  static wasm_valkind_enum fromValue(int value) => switch (value) {
    0 => WASM_I32,
    1 => WASM_I64,
    2 => WASM_F32,
    3 => WASM_F64,
    128 => WASM_EXTERNREF,
    129 => WASM_FUNCREF,
    _ => throw ArgumentError('Unknown value for wasm_valkind_enum: $value'),
  };
}

final class wasm_functype_t extends ffi.Opaque {}

final class wasm_externtype_t extends ffi.Opaque {}

enum wasm_externkind_enum {
  WASM_EXTERN_FUNC(0),
  WASM_EXTERN_GLOBAL(1),
  WASM_EXTERN_TABLE(2),
  WASM_EXTERN_MEMORY(3)
  ;

  final int value;
  const wasm_externkind_enum(this.value);

  static wasm_externkind_enum fromValue(int value) => switch (value) {
    0 => WASM_EXTERN_FUNC,
    1 => WASM_EXTERN_GLOBAL,
    2 => WASM_EXTERN_TABLE,
    3 => WASM_EXTERN_MEMORY,
    _ => throw ArgumentError('Unknown value for wasm_externkind_enum: $value'),
  };
}

final class wasm_importtype_t extends ffi.Opaque {}

final class wasm_importtype_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Pointer<wasm_importtype_t>> data;
}

final class wasm_exporttype_t extends ffi.Opaque {}

final class wasm_exporttype_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Pointer<wasm_exporttype_t>> data;
}

/// ////////////////////////////////////////////////////////////////////////////
final class wasm_ref_t extends ffi.Opaque {}

final class UnnamedUnion extends ffi.Union {
  @ffi.Int32()
  external int i32;

  @ffi.Int64()
  external int i64;

  @ffi.Float()
  external double f32;

  @ffi.Double()
  external double f64;

  external ffi.Pointer<wasm_ref_t> ref;
}

final class wasm_val_t extends ffi.Struct {
  @ffi.Uint8()
  external int kind;

  external UnnamedUnion of;
}

final class wasm_val_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<wasm_val_t> data;
}

final class wasm_instance_t extends ffi.Opaque {}

final class wasm_trap_t extends ffi.Opaque {}

final class wasm_module_t extends ffi.Opaque {}

final class wasm_func_t extends ffi.Opaque {}

typedef wasm_func_callback_t =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<wasm_trap_t> Function(ffi.Pointer<wasm_val_vec_t> args, ffi.Pointer<wasm_val_vec_t> results)
      >
    >;

final class wasm_memory_t extends ffi.Opaque {}

final class wasm_extern_t extends ffi.Opaque {}

final class wasm_extern_vec_t extends ffi.Struct {
  @ffi.Size()
  external int size;

  external ffi.Pointer<ffi.Pointer<wasm_extern_t>> data;
}

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int _WCHAR_T_DEFINED = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_CXX23 = 0;

const int _HAS_CXX26 = 0;

const int _HAS_NODISCARD = 1;

const int _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE = 1;

const int _CRT_BUILD_DESKTOP_APP = 1;

const int _UCRT_DISABLED_WARNINGS = 4324;

const int _ARGMAX = 100;

const int _TRUNCATE = -1;

const int _CRT_INT_MAX = 2147483647;

const int _CRT_SIZE_MAX = -1;

const String __FILEW__ = 'C';

const int _CRT_FUNCTIONS_REQUIRED = 1;

const int _CRT_HAS_CXX17 = 0;

const int _CRT_HAS_C11 = 0;

const int _CRT_INTERNAL_NONSTDC_NAMES = 1;

const int __STDC_SECURE_LIB__ = 200411;

const int __GOT_SECURE_LIB__ = 200411;

const int __STDC_WANT_SECURE_LIB__ = 1;

const int _SECURECRT_FILL_BUFFER_PATTERN = 254;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = 0;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES = 1;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY = 0;

const int _STATIC_INLINE_UCRT_FUNCTIONS = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -2147483648;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 2147483647;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 4294967295;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int WCHAR_MIN = 0;

const int WCHAR_MAX = 65535;

const int WINT_MIN = 0;

const int WINT_MAX = 65535;

const int __bool_true_false_are_defined = 1;

const int false$ = 0;

const int true$ = 1;

const int EPERM = 1;

const int ENOENT = 2;

const int ESRCH = 3;

const int EINTR = 4;

const int EIO = 5;

const int ENXIO = 6;

const int E2BIG = 7;

const int ENOEXEC = 8;

const int EBADF = 9;

const int ECHILD = 10;

const int EAGAIN = 11;

const int ENOMEM = 12;

const int EACCES = 13;

const int EFAULT = 14;

const int EBUSY = 16;

const int EEXIST = 17;

const int EXDEV = 18;

const int ENODEV = 19;

const int ENOTDIR = 20;

const int EISDIR = 21;

const int ENFILE = 23;

const int EMFILE = 24;

const int ENOTTY = 25;

const int EFBIG = 27;

const int ENOSPC = 28;

const int ESPIPE = 29;

const int EROFS = 30;

const int EMLINK = 31;

const int EPIPE = 32;

const int EDOM = 33;

const int EDEADLK = 36;

const int ENAMETOOLONG = 38;

const int ENOLCK = 39;

const int ENOSYS = 40;

const int ENOTEMPTY = 41;

const int EINVAL = 22;

const int ERANGE = 34;

const int EILSEQ = 42;

const int STRUNCATE = 80;

const int EDEADLOCK = 36;

const int EADDRINUSE = 100;

const int EADDRNOTAVAIL = 101;

const int EAFNOSUPPORT = 102;

const int EALREADY = 103;

const int EBADMSG = 104;

const int ECANCELED = 105;

const int ECONNABORTED = 106;

const int ECONNREFUSED = 107;

const int ECONNRESET = 108;

const int EDESTADDRREQ = 109;

const int EHOSTUNREACH = 110;

const int EIDRM = 111;

const int EINPROGRESS = 112;

const int EISCONN = 113;

const int ELOOP = 114;

const int EMSGSIZE = 115;

const int ENETDOWN = 116;

const int ENETRESET = 117;

const int ENETUNREACH = 118;

const int ENOBUFS = 119;

const int ENODATA = 120;

const int ENOLINK = 121;

const int ENOMSG = 122;

const int ENOPROTOOPT = 123;

const int ENOSR = 124;

const int ENOSTR = 125;

const int ENOTCONN = 126;

const int ENOTRECOVERABLE = 127;

const int ENOTSOCK = 128;

const int ENOTSUP = 129;

const int EOPNOTSUPP = 130;

const int EOTHER = 131;

const int EOVERFLOW = 132;

const int EOWNERDEAD = 133;

const int EPROTO = 134;

const int EPROTONOSUPPORT = 135;

const int EPROTOTYPE = 136;

const int ETIME = 137;

const int ETIMEDOUT = 138;

const int ETXTBSY = 139;

const int EWOULDBLOCK = 140;

const int _NLSCMPERROR = 2147483647;
