#!/usr/bin/env dart

// Compiles the TeaVM Jsoup bridge Java project to a minified JavaScript module,
// then writes lib/src/web/teavm_bundle.dart with the JS as a const string.
//
// Requirements: JDK 17+, Maven 3.x
//
// Usage:
//   dart run tool/build_teavm.dart
//
// The TeaVM project lives in tool/teavm/ and contains a thin Java wrapper
// (JsoupBridge.java) that delegates to the real Jsoup 1.18.3 library. TeaVM
// AOT-compiles the reachable bytecode to JavaScript, producing a UMD module
// that exports all NativeHtmlParser-equivalent methods.
// ignore_for_file: avoid_print
import 'dart:io';

void main() async {
  final String scriptDir = File(Platform.script.toFilePath()).parent.path;
  final String packageRoot = Directory('$scriptDir${Platform.pathSeparator}..').resolveSymbolicLinksSync();
  final teavmDir = '$packageRoot${Platform.pathSeparator}tool${Platform.pathSeparator}teavm';
  final outputPath =
      '$packageRoot'
      '${Platform.pathSeparator}lib'
      '${Platform.pathSeparator}src'
      '${Platform.pathSeparator}web'
      '${Platform.pathSeparator}teavm_bundle.dart';

  // Find Maven and Java.
  final mvnCmd = Platform.isWindows ? 'mvn.cmd' : 'mvn';
  final String? javaHome = Platform.environment['JAVA_HOME'];

  print('Building TeaVM Jsoup bridge ...');
  print('  TeaVM project: $teavmDir');
  if (javaHome != null) print('  JAVA_HOME: $javaHome');

  // Run Maven.
  final ProcessResult result = await Process.run(
    mvnCmd,
    <String>['clean', 'process-classes'],
    workingDirectory: teavmDir,
    environment: javaHome != null ? <String, String>{'JAVA_HOME': javaHome} : null,
  );
  if (result.exitCode != 0) {
    print('Maven stdout:\n${result.stdout}');
    print('Maven stderr:\n${result.stderr}');
    throw Exception('Maven build failed (exit code ${result.exitCode})');
  }
  print(result.stdout.toString().split('\n').where((String l) => l.contains('[INFO]')).join('\n'));

  // Read the compiled JS.
  final jsPath =
      '$teavmDir${Platform.pathSeparator}target${Platform.pathSeparator}js${Platform.pathSeparator}jsoup-bridge.js';
  final jsFile = File(jsPath);
  if (!jsFile.existsSync()) {
    throw Exception('TeaVM output not found at $jsPath');
  }
  final String js = await jsFile.readAsString();
  final int sizeKb = js.length ~/ 1024;
  print('TeaVM output: $sizeKb KB');

  // Generate Dart bundle file.
  // The JS contains single quotes in some places, so we use a triple-quoted
  // raw string delimited by triple-single-quotes. Any literal ''' in the JS
  // would break this, but TeaVM's minified output does not produce them.
  if (js.contains("'''")) {
    throw Exception(
      'TeaVM output contains triple single quotes — cannot embed as raw string literal. '
      'Use a different escaping strategy.',
    );
  }

  final buf = StringBuffer()
    ..writeln(
      '// Generated by tool/build_teavm.dart \u2014 do not edit by hand.',
    )
    ..writeln('// TeaVM-compiled Jsoup 1.18.3 bridge (UMD module, minified).')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln("const String teavmJsoupJs = r'''")
    ..write(js)
    ..writeln()
    ..writeln("''';");

  await File(outputPath).writeAsString(buf.toString());
  print('Wrote $outputPath');
}
