#!/usr/bin/env dart

// Bundles cheerio 1.2.0 into a standalone UMD file suitable for Web Workers,
// then writes lib/src/web/cheerio_bundle.dart with the JS as a const string.
//
// Requirements: Node.js, npm
//
// Usage:
//   dart run tool/bundle_cheerio.dart
//
// The transform strips `node:` import prefixes so browserify can resolve them
// to its built-in browser shims. `undici` is excluded (HTTP is handled by the
// worker separately).
// ignore_for_file: avoid_print
import 'dart:io';

const _cheerioVersion = '1.2.0';

void main() async {
  final String scriptDir = File(Platform.script.toFilePath()).parent.path;
  final String packageRoot = Directory('$scriptDir${Platform.pathSeparator}..').resolveSymbolicLinksSync();
  final outputPath =
      '$packageRoot'
      '${Platform.pathSeparator}lib'
      '${Platform.pathSeparator}src'
      '${Platform.pathSeparator}web'
      '${Platform.pathSeparator}cheerio_bundle.dart';

  final Directory tempDir = await Directory.systemTemp.createTemp('cheerio_bundle_');
  try {
    await _bundle(tempDir, outputPath);
  } finally {
    await tempDir.delete(recursive: true);
  }
}

Future<void> _bundle(Directory workDir, String outputPath) async {
  final String dir = workDir.path;
  final String sep = Platform.pathSeparator;

  // 1. Write helper files.
  await File('$dir${sep}entry.js').writeAsString(
    "module.exports = require('./node_modules/cheerio/dist/commonjs/index.js');\n",
  );

  // Transform: strip `node:` prefix so browserify resolves to browser shims.
  await File('$dir${sep}strip-node-prefix.js').writeAsString(r"""
const through = require('through2');
module.exports = function(file) {
  let data = '';
  return through(
    function(buf, enc, next) { data += buf; next(); },
    function(next) {
      this.push(data.replace(/require\(["']node:([^"']+)["']\)/g, 'require("$1")'));
      next();
    }
  );
};
""");

  // Build script.
  await File('$dir${sep}build.js').writeAsString('''
const browserify = require('browserify');
const fs = require('fs');
const path = require('path');
const b = browserify(path.join(__dirname, 'entry.js'), {
  standalone: 'cheerio',
  basedir: __dirname,
  transform: [[path.join(__dirname, 'strip-node-prefix.js'), { global: true }]],
});
b.ignore('undici');
b.bundle((err, buf) => {
  if (err) { console.error(err.message); process.exit(1); }
  fs.writeFileSync(path.join(__dirname, 'cheerio.bundle.js'), buf);
  console.log('Bundled:', buf.length, 'bytes');
});
''');

  // 2. npm install.
  print('Installing cheerio $_cheerioVersion + browserify ...');
  final ProcessResult installResult = await Process.run(
    'npm',
    <String>['install', 'cheerio@$_cheerioVersion', 'browserify', 'through2'],
    workingDirectory: dir,
  );
  if (installResult.exitCode != 0) {
    throw Exception('npm install failed:\n${installResult.stderr}');
  }

  // 3. Bundle.
  print('Bundling with browserify ...');
  final ProcessResult bundleResult = await Process.run(
    'node',
    <String>['build.js'],
    workingDirectory: dir,
  );
  if (bundleResult.exitCode != 0) {
    throw Exception('Bundle failed:\n${bundleResult.stderr}');
  }
  print(bundleResult.stdout);

  // 4. Minify with esbuild.
  print('Minifying ...');
  final ProcessResult minResult = await Process.run(
    'npx',
    <String>[
      'esbuild',
      'cheerio.bundle.js',
      '--minify',
      '--outfile=cheerio.min.js',
    ],
    workingDirectory: dir,
  );
  if (minResult.exitCode != 0) {
    // Fall back to un-minified if esbuild isn't available.
    print('esbuild minification failed, using un-minified bundle.');
    await File('$dir${sep}cheerio.bundle.js').copy('$dir${sep}cheerio.min.js');
  }

  // 5. Generate Dart file.
  final String js = await File('$dir${sep}cheerio.min.js').readAsString();
  final buf = StringBuffer()
    ..writeln(
      '// Generated by tool/bundle_cheerio.dart \u2014 do not edit by hand.',
    )
    ..writeln(
      '// cheerio $_cheerioVersion standalone UMD bundle (browserify + minified).',
    )
    ..writeln('// Provides self.cheerio global when executed in a Web Worker.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln("const String cheerioJs = r'''")
    ..write(js)
    ..writeln()
    ..writeln("''';");

  await File(outputPath).writeAsString(buf.toString());
  print('Wrote $outputPath (${buf.length} bytes)');
}
