import 'package:jsoup/src/html_parser.dart';
import 'package:objective_c/objective_c.dart' as objc;
import 'package:swiftsoup/swiftsoup.dart';

/// SwiftSoup-backed [NativeHtmlParser] for iOS and macOS.
///
/// Uses the SwiftSoupBridge @objc wrapper compiled from Swift, with Dart
/// bindings generated by ffigen. The bridge uses a handle-based pattern:
/// - `parse()` returns an opaque int handle
/// - Other methods accept handles to identify elements/node lists/text nodes
/// - `free()` releases a handle; `dispose()` releases all
class SwiftSoupParser implements NativeHtmlParser {
  // -- String helpers --

  static objc.NSString _ns(String s) => s.toNSString();

  static String? _str(objc.NSString? ns) => ns?.toString();

  static List<int> _handleList(objc.NSArray arr) {
    final int count = arr.count;
    final handles = <int>[];
    for (var i = 0; i < count; i++) {
      final num = objc.NSNumber.as(arr.objectAtIndex(i));
      handles.add(num.intValue);
    }
    return handles;
  }

  // -- Parsing --

  @override
  int parse(String html, {String baseUri = ''}) => SwiftSoupBridge.parse(_ns(html), baseUri: _ns(baseUri));

  @override
  int parseFragment(String html, {String baseUri = ''}) =>
      SwiftSoupBridge.parseFragment(_ns(html), baseUri: _ns(baseUri));

  // -- CSS Selectors --

  @override
  int select(int handle, String selector) => SwiftSoupBridge.select(handle, selector: _ns(selector));

  @override
  int selectFirst(int handle, String selector) => SwiftSoupBridge.selectFirst(handle, selector: _ns(selector));

  // -- Attributes --

  @override
  String? attr(int handle, String key) => _str(SwiftSoupBridge.attr(handle, key: _ns(key)));

  @override
  bool hasAttr(int handle, String key) => SwiftSoupBridge.hasAttr(handle, key: _ns(key));

  @override
  void setAttr(int handle, String key, String value) =>
      SwiftSoupBridge.setAttr(handle, key: _ns(key), value: _ns(value));

  @override
  void removeAttr(int handle, String key) => SwiftSoupBridge.removeAttr(handle, key: _ns(key));

  // -- Text & HTML --

  @override
  String? text(int handle) => _str(SwiftSoupBridge.text(handle));

  @override
  String? ownText(int handle) => _str(SwiftSoupBridge.ownText(handle));

  @override
  String? innerHtml(int handle) => _str(SwiftSoupBridge.innerHtml(handle));

  @override
  String? outerHtml(int handle) => _str(SwiftSoupBridge.outerHtml(handle));

  @override
  void setText(int handle, String text) => SwiftSoupBridge.setText(handle, text: _ns(text));

  @override
  void setHtml(int handle, String html) => SwiftSoupBridge.setHtml(handle, html: _ns(html));

  @override
  String? data(int handle) => _str(SwiftSoupBridge.data(handle));

  // -- Element Info --

  @override
  String? tagName(int handle) => _str(SwiftSoupBridge.tagName(handle));

  @override
  String? id(int handle) => _str(SwiftSoupBridge.elementId(handle));

  @override
  String? className(int handle) => _str(SwiftSoupBridge.className(handle));

  @override
  bool hasClass(int handle, String name) => SwiftSoupBridge.hasClass(handle, name: _ns(name));

  @override
  void addClass(int handle, String name) => SwiftSoupBridge.addClass(handle, name: _ns(name));

  @override
  void removeClass(int handle, String name) => SwiftSoupBridge.removeClass(handle, name: _ns(name));

  // -- Node list operations --

  @override
  int size(int handle) => SwiftSoupBridge.size(handle);

  @override
  int get(int handle, int index) => SwiftSoupBridge.get(handle, index: index);

  @override
  int first(int handle) => SwiftSoupBridge.first(handle);

  @override
  int last(int handle) => SwiftSoupBridge.last(handle);

  // -- Navigation --

  @override
  int parent(int handle) => SwiftSoupBridge.parent(handle);

  @override
  int children(int handle) => SwiftSoupBridge.children(handle);

  @override
  int nextSibling(int handle) => SwiftSoupBridge.nextSibling(handle);

  @override
  int prevSibling(int handle) => SwiftSoupBridge.prevSibling(handle);

  @override
  int siblings(int handle) => SwiftSoupBridge.siblings(handle);

  // -- Mutation --

  @override
  void remove(int handle) => SwiftSoupBridge.remove(handle);

  @override
  void prepend(int handle, String html) => SwiftSoupBridge.prepend(handle, html: _ns(html));

  @override
  void append(int handle, String html) => SwiftSoupBridge.append(handle, html: _ns(html));

  // -- Base URI --

  @override
  String? nodeBaseUri(int handle) => _str(SwiftSoupBridge.nodeBaseUri(handle));

  @override
  String? nodeAbsUrl(int handle, String key) => _str(SwiftSoupBridge.nodeAbsUrl(handle, key: _ns(key)));

  @override
  void setNodeBaseUri(int handle, String value) => SwiftSoupBridge.setNodeBaseUri(handle, value: _ns(value));

  // -- Element/TextNode creation --

  @override
  int createElement(String tag) => SwiftSoupBridge.createElement(_ns(tag));

  @override
  int createTextNode(String text) => SwiftSoupBridge.createTextNode(_ns(text));

  @override
  int createElements(List<int> elementHandles) {
    final objc.NSMutableArray nsArr = objc.NSMutableArray.alloc().init();
    for (final h in elementHandles) {
      nsArr.addObject(h.toNSNumber());
    }
    return SwiftSoupBridge.createElements(nsArr);
  }

  // -- Node-level methods --

  @override
  String? nodeName(int handle) => _str(SwiftSoupBridge.nodeName(handle));

  @override
  int childNodeSize(int handle) => SwiftSoupBridge.childNodeSize(handle);

  @override
  int childNode(int handle, int index) => SwiftSoupBridge.childNode(handle, index: index);

  @override
  List<int> childNodeHandles(int handle) => _handleList(SwiftSoupBridge.childNodeHandles(handle));

  @override
  bool isTextNode(int handle) => SwiftSoupBridge.isTextNode(handle);

  @override
  int parentNode(int handle) => SwiftSoupBridge.parentNode(handle);

  @override
  String? nodeOuterHtml(int handle) => _str(SwiftSoupBridge.nodeOuterHtml(handle));

  @override
  void removeNode(int handle) => SwiftSoupBridge.removeNode(handle);

  // -- Element-level --

  @override
  List<int> textNodeHandles(int handle) => _handleList(SwiftSoupBridge.textNodeHandles(handle));

  // -- TextNode-level --

  @override
  String? textNodeText(int handle) => _str(SwiftSoupBridge.textNodeText(handle));

  @override
  void setTextNodeText(int handle, String text) => SwiftSoupBridge.setTextNodeText(handle, text: _ns(text));

  @override
  String? textNodeWholeText(int handle) => _str(SwiftSoupBridge.textNodeWholeText(handle));

  @override
  bool textNodeIsBlank(int handle) => SwiftSoupBridge.textNodeIsBlank(handle);

  // -- Lifecycle --

  @override
  void free(int handle) => SwiftSoupBridge.free(handle);

  @override
  void releaseAll() => SwiftSoupBridge.releaseAll();

  @override
  void dispose() => SwiftSoupBridge.dispose();
}
